sonar.host.url=https://sonarcloud.io
sonar.login=c5cab4e227842a6aea71b71fe911831f7ceedaee
sonar.organization=ivandrizhiruk
sonar.projectKey=IvanDrizhiruk_big-brother

# relative paths to source directories. More details and properties are described
# in https://sonarcloud.io/documentation/project-administration/narrowing-the-focus/
sonar.sources=.
